spring:
  application:
    name: RealTimeAnalysis
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 32768 #Each batch size
      linger-ms: 10 #wait ms before sending batched data
      buffer-memory: 99108864
      compression-type: snappy #Compression types
      #Asnyc & Retry setting
      acks: 1 #send acknowledgement
      retries: 3
      retry-backoff-ms: 10
    consumer:
      max-poll-records: 100
      fetch-max-bytes: 5242880
      max-partition-fetch-bytes: 1048576
      enable-auto-commit: false
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%logger{36}:%L] - %msg%n"
kafka-topic: sp-ingest-trade-value
kafka-batch-size: 10000
