package rt.analysis.pojo;

public enum Country {
    NZ("New Zealand Dollars", "NZD", "New Zealand"),
    CK("New Zealand Dollars", "NZD", "Cook Islands"),
    NU("New Zealand Dollars", "NZD", "Niue"),
    PN("New Zealand Dollars", "NZD", "Pitcairn"),
    TK("New Zealand Dollars", "NZD", "Tokelau"),
    AU("Australian Dollars", "AUD", "Australian"),
    CX("Australian Dollars", "AUD", "Christmas Island"),
    CC("Australian Dollars", "AUD", "Cocos (Keeling) Islands"),
    HM("Australian Dollars", "AUD", "Heard and Mc Donald Islands"),
    KI("Australian Dollars", "AUD", "Kiribati"),
    NR("Australian Dollars", "AUD", "Nauru"),
    NF("Australian Dollars", "AUD", "Norfolk Island"),
    TV("Australian Dollars", "AUD", "Tuvalu"),
    AS("Euros", "EUR", "American Samoa"),
    AD("Euros", "EUR", "Andorra"),
    AT("Euros", "EUR", "Austria"),
    BE("Euros", "EUR", "Belgium"),
    FI("Euros", "EUR", "Finland"),
    FR("Euros", "EUR", "France"),
    GF("Euros", "EUR", "French Guiana"),
    TF("Euros", "EUR", "French Southern Territories"),
    DE("Euros", "EUR", "Germany"),
    GR("Euros", "EUR", "Greece"),
    GP("Euros", "EUR", "Guadeloupe"),
    IE("Euros", "EUR", "Ireland"),
    IT("Euros", "EUR", "Italy"),
    LU("Euros", "EUR", "Luxembourg"),
    MQ("Euros", "EUR", "Martinique"),
    YT("Euros", "EUR", "Mayotte"),
    MC("Euros", "EUR", "Monaco"),
    NL("Euros", "EUR", "Netherlands"),
    PT("Euros", "EUR", "Portugal"),
    RE("Euros", "EUR", "Reunion"),
    WS("Euros", "EUR", "Samoa"),
    SM("Euros", "EUR", "San Marino"),
    SI("Euros", "EUR", "Slovenia"),
    ES("Euros", "EUR", "Spain"),
    VA("Euros", "EUR", "Vatican City State (Holy See)"),
    GS("Sterling", "GBP", "South Georgia and the South Sandwich Islands"),
    GB("Sterling", "GBP", "United Kingdom"),
    JE("Sterling", "GBP", "Jersey"),
    IO("USD", "USD", "British Indian Ocean Territory"),
    GU("USD", "USD", "Guam"),
    MH("USD", "USD", "Marshall Islands"),
    FM("USD", "USD", "Micronesia Federated States of"),
    MP("USD", "USD", "Northern Mariana Islands"),
    PW("USD", "USD", "Palau"),
    PR("USD", "USD", "Puerto Rico"),
    TC("USD", "USD", "Turks and Caicos Islands"),
    US("USD", "USD", "United States"),
    UM("USD", "USD", "United States Minor Outlying Islands"),
    VG("USD", "USD", "Virgin Islands (British)"),
    VI("USD", "USD", "Virgin Islands (US)"),
    HK("HKD", "HKD", "Hong Kong"),
    CA("Canadian Dollar", "CAD", "Canada"),
    JP("Japanese Yen", "JPY", "Japan"),
    AF("Afghani", "AFN", "Afghanistan"),
    AL("Lek", "ALL", "Albania"),
    DZ("Algerian Dinar", "DZD", "Algeria"),
    AI("East Caribbean Dollar", "XCD", "Anguilla"),
    AG("East Caribbean Dollar", "XCD", "Antigua and Barbuda"),
    DM("East Caribbean Dollar", "XCD", "Dominica"),
    GD("East Caribbean Dollar", "XCD", "Grenada"),
    MS("East Caribbean Dollar", "XCD", "Montserrat"),
    KN("East Caribbean Dollar", "XCD", "Saint Kitts"),
    LC("East Caribbean Dollar", "XCD", "Saint Lucia"),
    VC("East Caribbean Dollar", "XCD", "Saint Vincent Grenadines"),
    AR("Peso", "ARS", "Argentina"),
    AM("Dram", "AMD", "Armenia"),
    AW("Netherlands Antilles Guilder", "ANG", "Aruba"),
    AN("Netherlands Antilles Guilder", "ANG", "Netherlands Antilles"),
    AZ("Manat", "AZN", "Azerbaijan"),
    BS("Bahamian Dollar", "BSD", "Bahamas"),
    BH("Bahraini Dinar", "BHD", "Bahrain"),
    BD("Taka", "BDT", "Bangladesh"),
    BB("Barbadian Dollar", "BBD", "Barbados"),
    BY("Belarus Ruble", "BYR", "Belarus"),
    BZ("Belizean Dollar", "BZD", "Belize"),
    BJ("CFA Franc BCEAO", "XOF", "Benin"),
    BF("CFA Franc BCEAO", "XOF", "Burkina Faso"),
    GW("CFA Franc BCEAO", "XOF", "Guinea-Bissau"),
    CI("CFA Franc BCEAO", "XOF", "Ivory Coast"),
    ML("CFA Franc BCEAO", "XOF", "Mali"),
    NE("CFA Franc BCEAO", "XOF", "Niger"),
    SN("CFA Franc BCEAO", "XOF", "Senegal"),
    TG("CFA Franc BCEAO", "XOF", "Togo"),
    BM("Bermudian Dollar", "BMD", "Bermuda"),
    BT("Indian Rupee", "INR", "Bhutan"),
    IN("Indian Rupee", "INR", "India"),
    BO("Boliviano", "BOB", "Bolivia"),
    BW("Pula", "BWP", "Botswana"),
    BV("Norwegian Krone", "NOK", "Bouvet Island"),
    NO("Norwegian Krone", "NOK", "Norway"),
    SJ("Norwegian Krone", "NOK", "Svalbard and Jan Mayen Islands"),
    BR("Brazil", "BRL", "Brazil"),
    BN("Bruneian Dollar", "BND", "Brunei Darussalam"),
    BG("Lev", "BGN", "Bulgaria"),
    BI("Burundi Franc", "BIF", "Burundi"),
    KH("Riel", "KHR", "Cambodia"),
    CM("CFA Franc BEAC", "XAF", "Cameroon"),
    CF("CFA Franc BEAC", "XAF", "Central African Republic"),
    TD("CFA Franc BEAC", "XAF", "Chad"),
    CG("CFA Franc BEAC", "XAF", "Congo Republic of the Democratic"),
    GQ("CFA Franc BEAC", "XAF", "Equatorial Guinea"),
    GA("CFA Franc BEAC", "XAF", "Gabon"),
    CV("Escudo", "CVE", "Cape Verde"),
    KY("Caymanian Dollar", "KYD", "Cayman Islands"),
    CL("Chilean Peso", "CLP", "Chile"),
    CN("Yuan Renminbi", "CNY", "China"),
    CO("Peso", "COP", "Colombia"),
    KM("Comoran Franc", "KMF", "Comoros"),
    CD("Congolese Frank", "CDF", "Congo-Brazzaville"),
    CR("Costa Rican Colon", "CRC", "Costa Rica"),
    HR("Croatian Dinar", "HRK", "Croatia (Hrvatska)"),
    CU("Cuban Peso", "CUP", "Cuba"),
    CY("Cypriot Pound", "CYP", "Cyprus"),
    CZ("Koruna", "CZK", "Czech Republic"),
    DK("Danish Krone", "DKK", "Denmark"),
    FO("Danish Krone", "DKK", "Faroe Islands"),
    GL("Danish Krone", "DKK", "Greenland"),
    DJ("Djiboutian Franc", "DJF", "Djibouti"),
    DO("Dominican Peso", "DOP", "Dominican Republic"),
    TP("Indonesian Rupiah", "IDR", "East Timor"),
    ID("Indonesian Rupiah", "IDR", "Indonesia"),
    EC("Sucre", "ECS", "Ecuador"),
    EG("Egyptian Pound", "EGP", "Egypt"),
    SV("Salvadoran Colon", "SVC", "El Salvador"),
    ER("Ethiopian Birr", "ETB", "Eritrea"),
    ET("Ethiopian Birr", "ETB", "Ethiopia"),
    EE("Estonian Kroon", "EEK", "Estonia"),
    FK("Falkland Pound", "FKP", "Falkland Islands (Malvinas)"),
    FJ("Fijian Dollar", "FJD", "Fiji"),
    PF("CFP Franc", "XPF", "French Polynesia"),
    NC("CFP Franc", "XPF", "New Caledonia"),
    WF("CFP Franc", "XPF", "Wallis and Futuna Islands"),
    GM("Dalasi", "GMD", "Gambia"),
    GE("Lari", "GEL", "Georgia"),
    GI("Gibraltar Pound", "GIP", "Gibraltar"),
    GT("Quetzal", "GTQ", "Guatemala"),
    GN("Guinean Franc", "GNF", "Guinea"),
    GY("Guyanaese Dollar", "GYD", "Guyana"),
    HT("Gourde", "HTG", "Haiti"),
    HN("Lempira", "HNL", "Honduras"),
    HU("Forint", "HUF", "Hungary"),
    IS("Icelandic Krona", "ISK", "Iceland"),
    IR("Iranian Rial", "IRR", "Iran (Islamic Republic of)"),
    IQ("Iraqi Dinar", "IQD", "Iraq"),
    IL("Shekel", "ILS", "Israel"),
    JM("Jamaican Dollar", "JMD", "Jamaica"),
    JO("Jordanian Dinar", "JOD", "Jordan"),
    KZ("Tenge", "KZT", "Kazakhstan"),
    KE("Kenyan Shilling", "KES", "Kenya"),
    KP("Won", "KPW", "Korea North"),
    KR("Won", "KRW", "Korea South"),
    KW("Kuwaiti Dinar", "KWD", "Kuwait"),
    KG("Som", "KGS", "Kyrgyzstan"),
    LA("Kip", "LAK", "Lao PeopleÕs Democratic Republic"),
    LV("Lat", "LVL", "Latvia"),
    LB("Lebanese Pound", "LBP", "Lebanon"),
    LS("Loti", "LSL", "Lesotho"),
    LR("Liberian Dollar", "LRD", "Liberia"),
    LY("Libyan Dinar", "LYD", "Libyan Arab Jamahiriya"),
    LI("Swiss Franc", "CHF", "Liechtenstein"),
    CH("Swiss Franc", "CHF", "Switzerland"),
    LT("Lita", "LTL", "Lithuania"),
    MO("Pataca", "MOP", "Macau"),
    MK("Denar", "MKD", "Macedonia"),
    MG("Malagasy Franc", "MGA", "Madagascar"),
    MW("Malawian Kwacha", "MWK", "Malawi"),
    MY("Ringgit", "MYR", "Malaysia"),
    MV("Rufiyaa", "MVR", "Maldives"),
    MT("Maltese Lira", "MTL", "Malta"),
    MR("Ouguiya", "MRO", "Mauritania"),
    MU("Mauritian Rupee", "MUR", "Mauritius"),
    MX("Peso", "MXN", "Mexico"),
    MD("Leu", "MDL", "Moldova Republic of"),
    MN("Tugrik", "MNT", "Mongolia"),
    MA("Dirham", "MAD", "Morocco"),
    EH("Dirham", "MAD", "Western Sahara"),
    MZ("Metical", "MZN", "Mozambique"),
    MM("Kyat", "MMK", "Myanmar"),
    NA("Dollar", "NAD", "Namibia"),
    NP("Nepalese Rupee", "NPR", "Nepal"),
    NI("Cordoba Oro", "NIO", "Nicaragua"),
    NG("Naira", "NGN", "Nigeria"),
    OM("Sul Rial", "OMR", "Oman"),
    PK("Rupee", "PKR", "Pakistan"),
    PA("Balboa", "PAB", "Panama"),
    PG("Kina", "PGK", "Papua New Guinea"),
    PY("Guarani", "PYG", "Paraguay"),
    PE("Nuevo Sol", "PEN", "Peru"),
    PH("Peso", "PHP", "Philippines"),
    PL("Zloty", "PLN", "Poland"),
    QA("Rial", "QAR", "Qatar"),
    RO("Leu", "RON", "Romania"),
    RU("Ruble", "RUB", "Russian Federation"),
    RW("Rwanda Franc", "RWF", "Rwanda"),
    ST("Dobra", "STD", "Sao Tome and Principe"),
    SA("Riyal", "SAR", "Saudi Arabia"),
    SC("Rupee", "SCR", "Seychelles"),
    SL("Leone", "SLL", "Sierra Leone"),
    SG("Dollar", "SGD", "Singapore"),
    SK("Koruna", "SKK", "Slovakia (Slovak Republic)"),
    SB("Solomon Islands Dollar", "SBD", "Solomon Islands"),
    SO("Shilling", "SOS", "Somalia"),
    ZA("Rand", "ZAR", "South Africa"),
    LK("Rupee", "LKR", "Sri Lanka"),
    SD("Dinar", "SDG", "Sudan"),
    SR("Surinamese Guilder", "SRD", "Suriname"),
    SZ("Lilangeni", "SZL", "Swaziland"),
    SE("Krona", "SEK", "Sweden"),
    SY("Syrian Pound", "SYP", "Syrian Arab Republic"),
    TW("Dollar", "TWD", "Taiwan"),
    TJ("Tajikistan Ruble", "TJS", "Tajikistan"),
    TZ("Shilling", "TZS", "Tanzania"),
    TH("Baht", "THB", "Thailand"),
    TO("PaÕanga", "TOP", "Tonga"),
    TT("Trinidad and Tobago Dollar", "TTD", "Trinidad and Tobago"),
    TN("Tunisian Dinar", "TND", "Tunisia"),
    TR("Lira", "TRY", "Turkey"),
    TM("Manat", "TMT", "Turkmenistan"),
    UG("Shilling", "UGX", "Uganda"),
    UA("Hryvnia", "UAH", "Ukraine"),
    AE("Dirham", "AED", "United Arab Emirates"),
    UY("Peso", "UYU", "Uruguay"),
    UZ("Som", "UZS", "Uzbekistan"),
    VU("Vatu", "VUV", "Vanuatu"),
    VE("Bolivar", "VEF", "Venezuela"),
    VN("Dong", "VND", "Vietnam"),
    YE("Rial", "YER", "Yemen"),
    ZM("Kwacha", "ZMK", "Zambia"),
    ZW("Zimbabwe Dollar", "ZWD", "Zimbabwe"),
    AX("Euro", "EUR", "Aland Islands"),
    AO("Angolan kwanza", "AOA", "Angola"),
    AQ("Antarctican dollar", "AQD", "Antarctica"),
    BA("Bosnia and Herzegovina convertible mark", "BAM", "Bosnia and Herzegovina"),
    GH("Ghana cedi", "GHS", "Ghana"),
    GG("Guernsey pound", "GGP", "Guernsey"),
    IM("Manx pound", "GBP", "Isle of Man"),
    ME("Euro", "EUR", "Montenegro"),
    PS("Jordanian dinar", "JOD", "Palestinian Territory"),
    BL("Euro", "EUR", "Saint Barthelemy"),
    SH("Saint Helena pound", "GBP", "Saint Helena"),
    MF("Netherlands Antillean guilder", "ANG", "Saint Martin (French part)"),
    PM("Euro", "EUR", "Saint Pierre and Miquelon"),
    RS("Serbian dinar", "RSD", "Serbia"),
    USAF("US Dollar", "USD", "US Armed Forces");
    private final String country;
    private final String currency;
    private final String currencyCode;

    private Country(String currency, String currencyCode, String country) {
        this.country = country;
        this.currency = currency;
        this.currencyCode = currencyCode;
    }

    public String getCountry() {
        return this.country;
    }

    public String getCurrency() {
        return this.currency;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    private final static Country[] countries = values();
    public static Country getByValue(int index){
        return countries[index];
    }

}
